image: python:3.11

definitions:
  services:
    broker:
      image: rabbitmq:3
      ports:
        - 5672:5672
  steps:
    - step: &lint
        caches:
          - pip
        name: Lint
        script:
          - pip install pre-commit
          - pre-commit install
          - pre-commit run --all-files
    - step: &test-311
        caches:
          - pip
        name: Test Python 3.11
        script:
          - pip install -U pip
          - pip install tox
          - tox -e py311
        services:
          - broker
    - step: &test311-min
        image: python:3.11
        caches:
          - pip
        name: Test Python 3.11 - Minimum
        script:
          - pip install -U pip
          - pip install tox
          - tox run -e py311-min
        services:
          - broker
    - step: &scan
        caches:
          - pip
        name: Scan
        script:
          - pip install .
          - pip freeze | grep -v @ > requirements.txt
          - cat requirements.txt
          - echo $SNYK_VERSION
          - curl -L -o snyk https://github.com/snyk/snyk/releases/download/$SNYK_VERSION/snyk-linux
          - chmod 755 snyk
          - ./snyk -d auth $SNYK_TOKEN
          - echo $SNYK_IGNORE
          - for id in $SNYK_IGNORE; do echo Ignoring $id; ./snyk ignore $id; done
          - cat .snyk || echo "No .snyk found. Probably because there was nothing to ignore."
          - echo $SNYK_CLI_COMMAND
          - $SNYK_CLI_COMMAND
    - step: &publish
        caches:
          - pip
        name: Publish
        script:
          - pip install -U pip
          - pip install twine build
          - python -m build --outdir wheelhouse .
          - python -m twine upload --skip-existing wheelhouse/*


pipelines:
  default:
    - step: *lint
    - parallel:
      - step: *test-311
      - step: *test311-min
    - step: *scan
  tags:
    'v*':
      - parallel:
          - step: *lint
          - step: *test-311
          - step: *test311-min
          - step: *scan
      - step: *publish
