# SPDX-FileCopyrightText: Enno Hermann
#
# SPDX-License-Identifier: MIT

[project]
name = "monotonic-alignment-search"
version = "0.1.0"
description = "Monotonically align text and speech"
readme = "README.md"
authors = [
    { name = "Jaehyeon Kim", email = "jaywalnut310@gmail.com" }
]
maintainers = [
    { name = "Enno Hermann", email = "enno.hermann@gmail.com" }
]
requires-python = ">=3.9"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Multimedia :: Sound/Audio :: Speech",
]
dependencies = [
    "numpy>=1.21.6; python_version < '3.11'",
    "numpy>=1.24.4; python_version == '3.11'",
    "numpy>=1.26.4; python_version == '3.12'",
    "numpy>=2.1.3; python_version == '3.13'",
    "torch>=1.12.1; python_version < '3.11'",
    "torch>=2.1.1; python_version == '3.11'",
    "torch>=2.2; python_version == '3.12'",
    "torch>=2.5.1; python_version == '3.13'",
]

[project.urls]
Repository = "https://github.com/eginhard/monotonic_alignment_search"
Issues = "https://github.com/eginhard/monotonic_alignment_search/issues"

[build-system]
requires = [
    "setuptools>=61",
    "cython>=3.0.0",
    "numpy>=2.0.0",
]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "coverage>=7.6.4",
    "mypy>=1.13.0",
    "pre-commit>=4.0.1",
    "pytest>=8.3.3",
    "reuse>=4.0.3",
    "ruff>=0.7.2",
]

[tool.ruff.lint]
select = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D104"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.coverage.report]
show_missing = true
skip_empty = true

[tool.coverage.run]
source = ["src/monotonic_alignment_search", "tests"]
command_line = "-m pytest"

[tool.cibuildwheel]
build = "cp*"
skip = "*-win32 *i686"
