[project]
name = "gembatch"
version = "0.0.13"
authors = [{ name = "Benno Lin", email = "blueworrybear@gmail.com" }]
description = """\
A Python library simplifies building language chain applications with Gemini, \
leveraging batch mode for cost-effective prompt processing.\
"""
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'google-cloud-aiplatform>=1.38',
    'firebase-admin>=6.5.0',
    'firebase-functions>=0.4.2',
    'requests>=2.31.0',
]
[project.urls]
Homepage = "https://github.com/blueworrybear/gembatch"
Issues = "https://github.com/blueworrybear/gembatch/issues"
