[project]
name = "unstract-client"
dynamic = []
description = "Python client for the Unstract LLM-powered structured data extraction platform"
authors = [
    { name = "Zipstack Inc", email = "devsupport@zipstack.com" },
]
dependencies = [
    "requests>=2.32.3",
]
requires-python = ">=3.11"
readme = "README.md"
keywords = [
    "unstract cli apps sdk",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
version = "1.0.0"

[project.urls]
Homepage = "https://unstract.com"
Source = "https://github.com/Zipstack/unstract-python-client"

[project.license]
text = "MIT"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=8.2.2",
    "pytest-mock>=3.14.0",
    "pytest-dotenv>=0.5.2",
    "pytest-cov>=5.0.0",
    "pytest-md-report>=0.6.2",
]
lint = [
    "autopep8~=2.0.2",
    "black~=23.3.0",
    "docutils~=0.20.1",
    "flake8~=6.0.0",
    "flake8-pyproject~=1.2.2",
    "isort~=5.12.0",
    "pre-commit~=3.3.1",
    "yamllint>=1.35.1",
    "mypy~=1.10.0",
]

[tool.pdm.version]
source = "file"
path = "src/unstract/api_deployments/__init__.py"

[tool.pdm.build]
includes = [
    "src",
]
package-dir = "src"

[tool.pdm.scripts.test]
cmd = "pytest -s -v"
env_file = "tests/.env"
help = "Runs pytests for Unstract client"

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
profile = "black"

[tool.flake8]
max-line-length = 88

[tool.pytest.ini_options]
env_files = [
    "tests/.env",
]
addopts = "-s"
log_level = "INFO"
log_cli = true

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
