# Developer(s): Grigori Fursin

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
name = "cmx4flex"

authors = [
    {name = "Grigori Fursin"}
]

version = "0.5.0"

description = "CMX bootstrapper for Flex automations"

requires-python = ">=3.8"

dependencies = [
    "setuptools",
    "cmind>=3.3.4",
    "flextask"
]

keywords = [
    "cmx4flex"
]

license = {text = "Apache Software License (Apache 2.0)"}

classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dynamic = ["readme"]

[tool.setuptools.dynamic]
readme = {file = "README.md", content-type = "text/markdown"}

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
where = ["."]
include = ["cmx4flex"]
exclude = ["docs", "docs.*", "tests", "tests.*"]

[project.scripts]
cmx4flex = "cmx4flex.main:init"
