[tool.poetry]
name = "talp-pages"
version = "3.5.0a8"
description = "Command line tools to generate performance reports using the TALP module of DLB"
authors = ["Valentin Seitz <valentin.seitz@bsc.es>"]
maintainers = ["Valentin Seitz <valentin.seitz@bsc.es>"]
readme = "README.md"
license = "GPL-3.0-only"
keywords = ["HPC", "Performance Analysis","Profiling","Continuous Performance Analysis"]
classifiers = [
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: System :: Distributed Computing"
]

homepage = "https://pm.bsc.es/gitlab/dlb/dlb/"
repository= "https://pm.bsc.es/gitlab/dlb/dlb/"


include = [
    "talp_pages/templates/*.jinja"
]

[tool.poetry.dependencies]
python = "^3.9"
python-gitlab = "^4.4.0"
jinja2 = "^3.1.4"
pandas = "^2.2.2"
plotly = "*"
kaleido = "0.2.1"

[tool.poetry.group.dev.dependencies]  
pytest-sugar = "*"  
pytest-cov = "*"  
black = "*"  
tox = "*"
ruff = "*"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.1"
coverage = "^7.6.0"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["talp_pages"]
branch = true
command_line = "-m pytest tests"

[tool.coverage.report]
show_missing = true

[tool.coverage.xml]
output = "coverage.xml"


[tool.poetry.scripts]
talp_download_artifacts_gitlab = 'talp_pages.cli.download_artifacts_gitlab:main'
talp = 'talp_pages.talp:main'
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
