[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cosmax"
version = "0.0.5"
authors = [
  { name="Andrin Rehmann", email="andrinrehmann@gmail.com" },
]
description = "Fast and differentiable implementations of operations needed for inference and analysis in cosmology. Powered by JAX"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "jax >=0.4.0",
  "optax >=0.2.0",
]

[project.urls]
Homepage = "https://andrinr.github.io/cosmax/"
Issues = "https://github.com/andrinr/cosmax/issues"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]