[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "SpringSaLaDpy"
version = "0.1.8"
authors = [
  { name="Harrison Perone", email="Harrison.perone@uconn.edu" },
]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "networkx",
    "ipykernel",
    "molclustpy",
    "setuptools==69.5.1"
]
description = "Run and visualize SpringSaLaD results from Python"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/MolClustPy/SpringSaLaD-Python-Viz"
Issues = "https://github.com/MolClustPy/SpringSaLaD-Python-Viz/issues"