[project]
name = "oanda-v20-client"
version = "0.1.4"
description = "A client library for accessing OANDA v20 REST API"
authors = [
    { name = "Takin Profit LLC", email = "takinprofit@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT License" }
dependencies = [
    "httpx>=0.20.0,<0.28.0",
    "attrs>=21.3.0",
    "python-dateutil>=2.8.0",
    "dacite>=1.8.1",
]

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"
