[project]
name = "geometric-sampling"
version = "0.3.0"
description = "Python package for Geometric Sampling Method"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.9.2",
    "numpy>=2.1.2",
    "tqdm>=4.66.5",
]
authors = [
    { name = "Bardia Panahbehagh", email = "bardia.panah@gmail.com" },
    { name = "Mehdi Mohebbi", email = "mehdi.mohebbi23@gmail.com" },
    { name = "AmirMohammad HosseiniNasab", email = "awmirhn@gmail.com" },
    { name = "Mehdi Hosseini Moghadam", email = "m.h.moghadam1996@gmail.com" }
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "mypy>=1.13.0",
    "notebook>=7.2.2",
    "ruff>=0.7.1",
    "types-tqdm>=4.66.0.20240417",
]

[tool.hatch.build.targets.wheel]
packages = ["geometric_sampling"]
