[tool.poetry]
name = "gg_daigua"
version = "0.2.0"
description = "方便的工具"
authors = ["邓润庭 <1032939141@qq.com>"]
readme = "README.md"
include = ["resources/**/*"]
packages = [
    { include = "gg" }
]

[tool.poetry.scripts]
gg = "gg.main:app"

[tool.poetry.dependencies]
python = "^3.12"
certifi = "2024.8.30"
charset-normalizer = "3.4.0"
colorama = "0.4.6"
decorator = "4.4.2"
filelock = "3.16.1"
fsspec = "2024.10.0"
idna = "3.10"
imageio = "2.36.0"
imageio-ffmpeg = "0.5.1"
jinja2 = "3.1.4"
llvmlite = "0.43.0"
markupsafe = "3.0.2"
more-itertools = "10.5.0"
moviepy = "1.0.3"
mpmath = "1.3.0"
networkx = "3.4.2"
numba = "0.60.0"
numpy = "2.0.2"
pillow = "11.0.0"
proglog = "0.1.10"
regex = "2024.9.11"
requests = "2.32.3"
six = "1.16.0"
sympy = "1.13.1"
tiktoken = "0.8.0"
torch = "2.5.1"
tqdm = "4.66.6"
typing-extensions = "4.12.2"
urllib3 = "2.2.3"
whisper = "1.1.10"
openai-whisper = "^20240930"
typer = "^0.12.5"
beautifulsoup4 = "^4.12.3"
pyexecjs = "^1.5.1"
ffmpeg-python = "^0.2.0"
psutil = "^6.1.0"
py7zr = "^0.22.0"


[tool.poetry.group.dev.dependencies]
twine = "^5.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
