[tool.poetry]
name = "restack_google_gemini"
version = "0.0.26"
description = "Google Gemini for Restack AI"
authors = [
    "Restack Team <service@restack.io>"
]
packages = [{ include = "restack_google_gemini", from = "src" }]
include = ["src/restack_google_gemini/py.typed"]

readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.9.2"
google-generativeai = "^0.8.3"
restack_ai = "^0.0.28"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"