[project]
name = "comfyui-idl"
description = "ComfyUI Interface Definition Language"
authors = [
    { name = "Frost Ming", email = "frost@bentoml.com" },
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pydantic>=2.9",
    "comfy-cli>=1.2.8",
]
dynamic = []
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
version = "0.0.4"

[project.urls]
Homepage = "https://github.com/bentoml/ComfyUI-BentoML"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = [
    "src/",
]

[tool.pdm.version]
source = "scm"
