[project]
name = "simplemind-chat"
version = "0.1.8"
description = "A chat interface for AI models using Simplemind."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "appdirs",
    "docopt",
    "rich",
    "prompt_toolkit",
    "xerox",
    "simplemind[full]",
    "spacy",
    "nltk",
]

[project.scripts]
simplechat = "simplechat.cli:main"
