[project]
name = "nameisok"
version = "0.1.6"
description = "A utility package for checking if a package name is available on PyPI."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Sermet Pekin", email = "Sermet.Pekin@gmail.com" }
]
license = {text = "MIT"}
keywords = ["pypi", "package availability", "name checker", "available", "utility"]
dependencies = [
    "fuzzywuzzy>=0.18.0",
    "pytest>=8.3.3",
    "python-levenshtein>=0.26.1",
    "requests>=2.32.3",
]

[project.urls]
repository = "https://github.com/SermetPekin/nameisok"
documentation = "https://github.com/SermetPekin/nameisok#readme"
issue_tracker = "https://github.com/SermetPekin/nameisok/issues"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
nameisok = "nameisok.cli:main"

[tool.setuptools]
packages = ["nameisok"]

[tool.setuptools.package-data]
nameisok = ["*"]

[tool.setuptools.exclude-package-data]
nameisok = ["raw/*"]


[tool.ruff]
exclude = [

    "*.ipynb",
    'ignore*.py'
#    "tests/*",
]

