[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["djreport", "djreport.*"]

[project]
name = "djreport"
version = "0.0.3"
dependencies = [
    "django>=5.1.1",
]
authors = [
  { name="Kaveh Mehrbanian", email="mehrbaniankaveh@gmail.com" },
]
description = "A Django app powered by Stimulsoft to make reporting easy"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/kavehkm/DJReport"
Documentation = "https://github.com/kavehkm/DJReport"
Issues = "https://github.com/kavehkm/DJReport/issues"