[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qmm-core"
version = "0.2.25"
authors = [
  { name="Jayden Hyman", email="j.hyman@uq.edu.au" },
]
description = "A software platform for analysing the structure and function of complex systems"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "pytest>=8.3.2",
    "numpy>=1.26.4,<1.28",
    "sympy>=1.11.1",
    "networkx>=2.6.3",
    "numba>=0.60.0",
    "pandas>=2.2.3",
    "seaborn>=0.13.2",
    "matplotlib>=3.9.2",
]

[project.urls]
"Homepage" = "https://github.com/jaydenhyman/qmm"
"Bug Tracker" = "https://github.com/jaydenhyman/qmm/issues"

[tool.setuptools.packages.find]
exclude = ["test*"]

[tool.setuptools.package-data]
qmm = ["py.typed"]
