[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chess-scraping"
version = "0.3.0"
authors = [
  {name="Marcel Claramunt", email="marcel@moveread.com"}
]
description = "Scraping from chess pairing websites"
dependencies = [
  "haskellian", "httpx", "bs4", "chess-pairings", "playwright",
]
requires-python = ">=3.10"
readme = {file="README.md", content-type="text/markdown"}

[project.urls]
repo = "https://github.com/moveread/scraping.git"

# [project.optional-dependencies]
# test = [
#   "pytest < 5.0.0",
#   "pytest-cov[all]"
# ]