[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["make87*"]

[project]
name = "make87"
version = "0.0.58"
authors = [
    { name = "Nisse Knudsen", email = "nisse@make87.com" },
]
dependencies = [
    "numpy",
    "protobuf==4.25.5",
    "eclipse-zenoh==1.0.0",
    "pydantic",
]
readme = "README.md"
requires-python = ">=3.9,<3.13"

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pytest",
    "pytest-mock"
]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-gen-files",
    "mkdocs-literate-nav",
    "mkdocs-section-index",
]
