[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pgmenus"
version = "0.0.30"
authors = [
  { name="Chris D", email="author@example.com" },
]
description = "A simple package to make menus inside pygame."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/christianlde/pgmenus"
Issues = "https://github.com/christianlde/pgmenus/issues"