[build-system]
requires = [
    "setuptools>=61.0",
    "wheel >= 0.29.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "water_column_sonar_processing"
version = "0.0.6"
authors = [
  { name="Rudy Klucik", email="rudy.klucik@noaa.gov" },
]
description = "A processing tool for water column sonar data."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]

[project.urls]
Homepage = "https://github.com/CI-CMG/water-column-sonar-processing"
Issues = "https://github.com/CI-CMG/water-column-sonar-processing/issues"

#[pytest]
#pythonpath = "src"
#testpaths = "tests"

[tool.pytest.ini_options]
minversion = "6.0"
#addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {dev = { file = ["requirements-dev.txt"] }}

# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/