
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.black]
line-length = 120
target-version = ["py37", "py38", "py39", "py310"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
include_trailing_comma = true
reverse_relative = true

[project]
name = "RareGO"
version = "0.0.21"
authors = [
  { name="Bradford Patton", email="bradfordpatton72@gmail.com" },
]
description = "A link prediction biomedical discovery package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

keywords = [
    "snekpack", # please keep this keyword to credit the cookiecutter-snekpack template
    "cookiecutter",
    "Knowledge Graph Embeddings",
    "Machine Learning",
    "Data Mining",
    "Linked Data",
]

dependencies = [
    "dataclasses-json",
    "numpy",
    "pykeen",
    "pykeen>=1.10.1",
    "numpy<2.0.0; sys_platform == 'win32'",
    "scipy>=1.7.0",
    "click",
    "click_default_group",
    "scikit-learn",
    "torch>=2.0,<2.4",
    "torchvision>=0.15.0,<0.17.0",
    "tqdm",
    "requests",
    "optuna>=2.0.0",
    "pandas>=1.0.0",
    "tabulate",
    "more_click",
    "more_itertools",
    "pystow>=0.4.3",
    "docdata",
    "class_resolver>0.4.2",
    "pyyaml",
    "torch_max_mem>=0.1.1",
    "torch-ppr>=0.0.7",
    "typing_extensions",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["rarego_kge"]

[tool.setuptools.package-data]
rarego_kge = ["data/*", "drugrepurposing/*", "example_trainings/*", "kgsearch/*", "training_code/*"]

[project.urls]
Homepage = "https://github.com/baseballtrout/RareGO-Capestone"
Issues = "https://github.com/baseballtrout/RareGO-Capestone/issues"